kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pglinter-test
# -----------------------------------------------
# 1. Enable the Feature Gate cluster-wide
# -----------------------------------------------
featureGates:
  ImageVolume: true
# -----------------------------------------------
