
name: 'Build and Test pglinter'

on:
  # pull_request:
  #   branches:
  #     - main  # Optional: specify branches for the pull request to merge into
  #   paths-ignore:
  #     - 'docs/**'
  #     - '*.md'
  #     - 'README.md'
  #     - 'mkdocs.yml'
  workflow_dispatch:
    inputs:
      pgversions:
        description: 'PostgreSQL versions to build (comma-separated: pg18)'
        required: false
        default: 'pg18'
        type: string
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ##
  ## B U I L D / T E S T
  ##
  build:
    strategy:
      matrix:
        #pgver: [pg14,pg15,pg16,pg17,pg18]
        pgver: [pg14]
      fail-fast: false
    name: 'build-and-tests-pglinter-for-${{ matrix.pgver }}'
    runs-on: ubuntu-latest
    # Use GitHub Container Registry for pmpetit
    container:
      image: ghcr.io/pmpetit/postgresql_pglinter:pgrx
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Call reusable build action
        uses: ./.github/actions/reusable-build-action
        with:
          pgver: ${{ matrix.pgver }}
          always: ${{ matrix.pgver == 'pg13' && 'yes' || '' }}
